/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PresentationLayer.AuxiliarAcademico;

import BusinessLayer.DocenteBO;
import BusinessLayer.EstudianteBO;
import BusinessLayer.UsuarioBO;
import DataTransferObject.Docente;
import DataTransferObject.Estudiante;
import DataTransferObject.Usuario;
import Utilities.Validator.ValidatorUsuario;
import javax.swing.JOptionPane;

public class Gestionar_docente_estudiantes extends javax.swing.JFrame {

    private String dni;
    private String nombreCompleto;
    private String correoElectronico;
    private Estudiante estudiante;
    private Docente docente;
    private Usuario usuario;
    
    public Gestionar_docente_estudiantes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nombreAuxiliarA = new javax.swing.JLabel();
        correoAuxiliarA = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcoRol = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jtxtDNI = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtApellidoPaterno = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtxtApellidoMaterno = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jcoGenero = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jcaFechaNacimiento = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jtxtNumeroTelefonico = new javax.swing.JTextField();
        jlGradoAcademico = new javax.swing.JLabel();
        jcoGradoAcademico = new javax.swing.JComboBox<>();
        jlEspecialidadAcademica = new javax.swing.JLabel();
        jcoEspecialidadAcademica = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jtxtCorreoElectronico = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(153, 255, 153));
        jPanel5.setPreferredSize(new java.awt.Dimension(1000, 1000));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setVerifyInputWhenFocusTarget(false);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/auxiliar academico.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Auxiliar Académico:");

        nombreAuxiliarA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nombreAuxiliarA.setText("Julio Perez Soto");

        correoAuxiliarA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        correoAuxiliarA.setText("Jperezsoto@gmail.com");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setText("GESTIONAR DOCENTES Y ESTUDIANTES");

        jLabel3.setText("Seleccione:");

        jcoRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Docente", "Estudiante" }));
        jcoRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcoRolActionPerformed(evt);
            }
        });

        jLabel4.setText("DNI:");

        jtxtDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtDNIKeyTyped(evt);
            }
        });

        jLabel5.setText("Nombre:");

        jtxtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtNombreKeyTyped(evt);
            }
        });

        jLabel6.setText("Apellido paterno:");

        jtxtApellidoPaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtApellidoPaternoKeyTyped(evt);
            }
        });

        jLabel9.setText("Apellido materno:");

        jtxtApellidoMaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtApellidoMaternoKeyTyped(evt);
            }
        });

        jLabel10.setText("Género:");

        jcoGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer" }));

        jLabel12.setText("Fecha de nacimiento:");

        jLabel13.setText("Número telefónico:");

        jtxtNumeroTelefonico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtNumeroTelefonicoKeyTyped(evt);
            }
        });

        jlGradoAcademico.setText("Grado académico:");

        jcoGradoAcademico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Licenciado", "Magister", "Doctor" }));

        jlEspecialidadAcademica.setText("Especialidad académica:");

        jcoEspecialidadAcademica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ciencias", "Humanidades" }));

        jLabel16.setText("Correo Electrónico");

        jtxtCorreoElectronico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtCorreoElectronicoKeyTyped(evt);
            }
        });

        jButton2.setMnemonic('b');
        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setMnemonic('r');
        jButton3.setText("Insertar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setMnemonic('m');
        jButton4.setText("Modificar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton10.setMnemonic('l');
        jButton10.setText("Eliminar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtApellidoPaterno)
                            .addComponent(jtxtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1777, 1777, 1777))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcaFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(54, 54, 54)
                                    .addComponent(jtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtxtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jcoGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jlGradoAcademico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcoGradoAcademico, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlEspecialidadAcademica)
                                .addGap(18, 18, 18)
                                .addComponent(jcoEspecialidadAcademica, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxtNumeroTelefonico, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxtCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4)
                                .addGap(27, 27, 27)
                                .addComponent(jButton10)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(correoAuxiliarA))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(nombreAuxiliarA)))))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel3)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jcoRol, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(1480, 1480, 1480))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nombreAuxiliarA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(correoAuxiliarA))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcoRol, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(13, 13, 13)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtDNI, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtxtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcoGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel12))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jcaFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jtxtNumeroTelefonico, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlGradoAcademico)
                    .addComponent(jcoGradoAcademico, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlEspecialidadAcademica)
                    .addComponent(jcoEspecialidadAcademica, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jtxtCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton10))
                .addGap(96, 96, 96))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Colegio_mayor_coar_logo (1) (3).png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel2.setText("COAR - INFINITE KNOWLEDGE");

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jButton1.setMnemonic('i');
        jButton1.setText("Inicio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(153, 255, 153));
        jButton5.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jButton5.setMnemonic('e');
        jButton5.setText("Enviar correos");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(153, 255, 153));
        jButton7.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jButton7.setMnemonic('n');
        jButton7.setText("Información personal");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(153, 255, 153));
        jButton8.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jButton8.setMnemonic('s');
        jButton8.setText("Subir reportes");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(153, 255, 153));
        jButton6.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jButton6.setMnemonic('a');
        jButton6.setText("Asignar cursos");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(153, 255, 153));
        jButton9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton9.setMnemonic('d');
        jButton9.setText("Docentes y Estudiantes");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(153, 255, 153));
        jButton11.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jButton11.setText("Asignar a estudiante");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton8)
                                .addGap(20, 20, 20))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton9))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton11)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel2))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(76, 76, 76)
                        .addComponent(jButton1)
                        .addGap(26, 26, 26)
                        .addComponent(jButton9)
                        .addGap(24, 24, 24)
                        .addComponent(jButton6)
                        .addGap(29, 29, 29)
                        .addComponent(jButton11)
                        .addGap(24, 24, 24)
                        .addComponent(jButton5)
                        .addGap(26, 26, 26)
                        .addComponent(jButton8)
                        .addGap(27, 27, 27)
                        .addComponent(jButton7)
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 863, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Pantalla_principal_auxiliar_academico ventana = new Pantalla_principal_auxiliar_academico();
        ventana.setDni(dni);
        ventana.setNombreCompleto(nombreCompleto);
        ventana.setCorreoElectronico(correoElectronico);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Enviar_correos_auxiliar_academico ventana = new Enviar_correos_auxiliar_academico();
        ventana.setDni(dni);
        ventana.setNombreCompleto(nombreCompleto);
        ventana.setCorreoElectronico(correoElectronico);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Ver_informacion_personal_auxiliar_academico ventana = new Ver_informacion_personal_auxiliar_academico();
        ventana.setDni(dni);
        ventana.setNombreCompleto(nombreCompleto);
        ventana.setCorreoElectronico(correoElectronico);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Subir_reportes_auxiliar_academico ventana = new Subir_reportes_auxiliar_academico();
        ventana.setDni(dni);
        ventana.setNombreCompleto(nombreCompleto);
        ventana.setCorreoElectronico(correoElectronico);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Asignar_cursos_auxiliar_academico ventana = new Asignar_cursos_auxiliar_academico();
        ventana.setDni(dni);
        ventana.setNombreCompleto(nombreCompleto);
        ventana.setCorreoElectronico(correoElectronico);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jtxtDNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtDNIKeyTyped
        char caracter = evt.getKeyChar(); 
        if(((caracter<'0')||(caracter>'9')) && ((caracter!='\b') || (caracter!='\t'))){
            evt.consume();
        }
        if(this.jtxtDNI.getText().length()==8) evt.consume();
    }//GEN-LAST:event_jtxtDNIKeyTyped

    private void jtxtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtNombreKeyTyped
        char caracter = evt.getKeyChar(); 
        if(!((caracter<'0')||(caracter>'9')) && ((caracter!='\b') || (caracter!='\t'))){
            evt.consume();
        }
        if(this.jtxtNombre.getText().length()==50) evt.consume();
    }//GEN-LAST:event_jtxtNombreKeyTyped

    private void jtxtApellidoPaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtApellidoPaternoKeyTyped
        char caracter = evt.getKeyChar(); 
        if(!((caracter<'0')||(caracter>'9')) && ((caracter!='\b') || (caracter!='\t'))){
            evt.consume();
        }
        if(this.jtxtApellidoPaterno.getText().length()==50) evt.consume();
    }//GEN-LAST:event_jtxtApellidoPaternoKeyTyped

    private void jtxtApellidoMaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtApellidoMaternoKeyTyped
        char caracter = evt.getKeyChar(); 
        if(!((caracter<'0')||(caracter>'9')) && ((caracter!='\b') || (caracter!='\t'))){
            evt.consume();
        }
        if(this.jtxtApellidoMaterno.getText().length()==50) evt.consume();
    }//GEN-LAST:event_jtxtApellidoMaternoKeyTyped

    private void jtxtNumeroTelefonicoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtNumeroTelefonicoKeyTyped
        char caracter = evt.getKeyChar(); 
        if(((caracter<'0')||(caracter>'9')) && ((caracter!='\b') || (caracter!='\t'))){
            evt.consume();
        }
        if(this.jtxtNumeroTelefonico.getText().length()==9) evt.consume();
    }//GEN-LAST:event_jtxtNumeroTelefonicoKeyTyped

    private void jtxtCorreoElectronicoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCorreoElectronicoKeyTyped
        if(this.jtxtCorreoElectronico.getText().length()==100) evt.consume();
    }//GEN-LAST:event_jtxtCorreoElectronicoKeyTyped

    private void jcoRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcoRolActionPerformed
        actualizarFormulario();
        limpiarDatos();
    }//GEN-LAST:event_jcoRolActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Buscar_docente_estudiante_auxiliar_academico ventana = new Buscar_docente_estudiante_auxiliar_academico();
        ventana.setDni(dni);
        ventana.setNombreCompleto(nombreCompleto);
        ventana.setCorreoElectronico(correoElectronico);
        ventana.setOption(this.jcoRol.getSelectedIndex()+2);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
            switch(this.jcoRol.getSelectedIndex()){
                case 0:
                    if(this.jtxtDNI.getText().equals("")){
                        JOptionPane.showMessageDialog(null, "Error, ingrese el DNI del Docente");
                    }
                    else if(this.jtxtDNI.getText().length()!=8){
                        JOptionPane.showMessageDialog(null, "Error, el DNI del Docente ingresado no posee la cantidad de caracteres adecuada (8)");
                    }
                    else if(this.jtxtNombre.getText().equals("")){
                         JOptionPane.showMessageDialog(null, "Error, ingrese el nombre del Docente");
                    }
                    else if(this.jtxtApellidoPaterno.getText().equals("")){
                         JOptionPane.showMessageDialog(null, "Error, ingrese el apellido paterno del Docente");
                    }
                    else if(this.jtxtApellidoMaterno.getText().equals("")){
                         JOptionPane.showMessageDialog(null, "Error, ingrese el apellido materno del Docente");
                    }
                    else if(this.jcaFechaNacimiento.getDate()==null){
                        JOptionPane.showMessageDialog(null, "Error, ingrese la fecha de nacimiento del Docente");
                    }
                    else if(this.jtxtNumeroTelefonico.getText().equals("")){
                        JOptionPane.showMessageDialog(null, "Error, ingrese el número telefónico del Docente");
                    }
                    else if(this.jtxtNumeroTelefonico.getText().length()!=9){
                        JOptionPane.showMessageDialog(null, "Error, el número telefónico del Docente ingresado no posee la cantidad de caracteres adecuada (9)");
                    }
                    else if(this.jtxtCorreoElectronico.getText().equals("")){
                        JOptionPane.showMessageDialog(null, "Error, ingrese el correo electrónico del Docente");
                    }
                    else if(!ValidatorUsuario.isEmail(this.jtxtCorreoElectronico.getText())){
                        JOptionPane.showMessageDialog(null, "Error, el correo electrónico del Docente posee un formato no adecuado");
                    }
                    else{
                        UsuarioBO usuarioBO = new UsuarioBO();
                        DocenteBO docenteBO = new DocenteBO();
                        
                        Docente docente = new Docente(0,this.jtxtDNI.getText(),this.jtxtNombre.getText(),this.jtxtApellidoPaterno.getText(),this.jtxtApellidoMaterno.getText(),
                        this.jcaFechaNacimiento.getDate(),this.jtxtNumeroTelefonico.getText(),(String) this.jcoGenero.getSelectedItem(),(String) this.jcoGradoAcademico.getSelectedItem(),
                        (String) this.jcoEspecialidadAcademica.getSelectedItem());

                        Usuario usuario = new Usuario(0,this.jtxtDNI.getText(),this.jtxtCorreoElectronico.getText(),this.jtxtDNI.getText()+"aasSAD__@@","3");
                        usuarioBO.insertar(usuario);

                        docenteBO.insertar(docente);

                        JOptionPane.showMessageDialog(null, "Docente registrado satisfactoriamente");
                    }
                    break;
                case 1:
                    if(this.jtxtDNI.getText().equals("")){
                        JOptionPane.showMessageDialog(null, "Error, ingrese el DNI del Estudiante");
                    }
                    else if(this.jtxtDNI.getText().length()!=8){
                        JOptionPane.showMessageDialog(null, "Error, el DNI del Estudiante ingresado no posee la cantidad de caracteres adecuada (8)");
                    }
                    else if(this.jtxtNombre.getText().equals("")){
                         JOptionPane.showMessageDialog(null, "Error, ingrese el nombre del Estudiante");
                    }
                    else if(this.jtxtApellidoPaterno.getText().equals("")){
                         JOptionPane.showMessageDialog(null, "Error, ingrese el apellido paterno del Estudiante");
                    }
                    else if(this.jtxtApellidoMaterno.getText().equals("")){
                         JOptionPane.showMessageDialog(null, "Error, ingrese el apellido materno del Estudiante");
                    }
                    else if(this.jcaFechaNacimiento.getDate()==null){
                        JOptionPane.showMessageDialog(null, "Error, ingrese la fecha de nacimiento del Estudiante");
                    }
                    else if(this.jtxtNumeroTelefonico.getText().equals("")){
                        JOptionPane.showMessageDialog(null, "Error, ingrese el número telefónico del Estudiante");
                    }
                    else if(this.jtxtNumeroTelefonico.getText().length()!=9){
                        JOptionPane.showMessageDialog(null, "Error, el número telefónico del Estudiante ingresado no posee la cantidad de caracteres adecuada (9)");
                    }
                    else if(this.jtxtCorreoElectronico.getText().equals("")){
                        JOptionPane.showMessageDialog(null, "Error, ingrese el correo electrónico del Estudiante");
                    }
                    else if(!ValidatorUsuario.isEmail(this.jtxtCorreoElectronico.getText())){
                        JOptionPane.showMessageDialog(null, "Error, el correo electrónico del Docente posee un formato no adecuado");
                    }
                    else{
                        UsuarioBO usuarioBO = new UsuarioBO();
                        EstudianteBO estudianteBO = new EstudianteBO();
                        
                        Estudiante estudiante = new Estudiante(0,this.jtxtDNI.getText(),this.jtxtNombre.getText(),this.jtxtApellidoPaterno.getText(),this.jtxtApellidoMaterno.getText(),
                        this.jcaFechaNacimiento.getDate(),this.jtxtNumeroTelefonico.getText(),(String) this.jcoGenero.getSelectedItem());

                        Usuario usuario = new Usuario(0,this.jtxtDNI.getText(),this.jtxtCorreoElectronico.getText(),this.jtxtDNI.getText()+"aasSAD__@@","4");
                        usuarioBO.insertar(usuario);

                        estudianteBO.insertar(estudiante);

                        JOptionPane.showMessageDialog(null, "Estudiante registrado satisfactoriamente");
                    }
                    break;
            }
        }
        catch(Exception e){
            if(e.getMessage().contains("idx_docente_dni")){
                JOptionPane.showMessageDialog(null, "El DNI ingresado del docente ya existe en la base de datos");
            }
            if(e.getMessage().contains("idx_docente_numero_telefonico")){
                JOptionPane.showMessageDialog(null, "El numero telefonico ingresado del docente ya existe en la base de datos");
            }
            
            if(e.getMessage().contains("idx_estudiante_dni")){
                JOptionPane.showMessageDialog(null, "El DNI ingresado del estudiante ya existe en la base de datos");
            }
            if(e.getMessage().contains("idx_estudiante_numero_telefonico")){
                JOptionPane.showMessageDialog(null, "E-003: El numero telefonico ingresado del estudiante ya existe en la base de datos");
            }
            
            if(e.getMessage().contains("idx_usuario_correo_electronico")){
                JOptionPane.showMessageDialog(null, "El correo electronico ingresado ya existe en la base de datos");
            }
            
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
            switch(this.jcoRol.getSelectedIndex()){
                case 0:
                    if(this.jtxtDNI.getText().equals("")){
                        JOptionPane.showMessageDialog(null, "Error, ingrese el DNI del Docente");
                    }
                    else if(this.jtxtDNI.getText().length()!=8){
                        JOptionPane.showMessageDialog(null, "Error, el DNI del Docente ingresado no posee la cantidad de caracteres adecuada (8)");
                    }
                    else if(this.jtxtNombre.getText().equals("")){
                         JOptionPane.showMessageDialog(null, "Error, ingrese el nombre del Docente");
                    }
                    else if(this.jtxtApellidoPaterno.getText().equals("")){
                         JOptionPane.showMessageDialog(null, "Error, ingrese el apellido paterno del Docente");
                    }
                    else if(this.jtxtApellidoMaterno.getText().equals("")){
                         JOptionPane.showMessageDialog(null, "Error, ingrese el apellido materno del Docente");
                    }
                    else if(this.jcaFechaNacimiento.getDate()==null){
                        JOptionPane.showMessageDialog(null, "Error, ingrese la fecha de nacimiento del Docente");
                    }
                    else if(this.jtxtNumeroTelefonico.getText().equals("")){
                        JOptionPane.showMessageDialog(null, "Error, ingrese el número telefónico del Docente");
                    }
                    else if(this.jtxtNumeroTelefonico.getText().length()!=9){
                        JOptionPane.showMessageDialog(null, "Error, el número telefónico del Docente ingresado no posee la cantidad de caracteres adecuada (9)");
                    }
                    else if(this.jtxtCorreoElectronico.getText().equals("")){
                        JOptionPane.showMessageDialog(null, "Error, ingrese el correo electrónico del Docente");
                    }
                    else if(!ValidatorUsuario.isEmail(this.jtxtCorreoElectronico.getText())){
                        JOptionPane.showMessageDialog(null, "Error, el correo electrónico del Docente posee un formato no adecuado");
                    }
                    else{
                        UsuarioBO usuarioBO = new UsuarioBO();
                        DocenteBO docenteBO = new DocenteBO();
                        
                        Docente docente = new Docente(this.getDocente().getIdMiembro(),this.jtxtDNI.getText(),this.jtxtNombre.getText(),this.jtxtApellidoPaterno.getText(),this.jtxtApellidoMaterno.getText(),
                        this.jcaFechaNacimiento.getDate(),this.jtxtNumeroTelefonico.getText(),(String) this.jcoGenero.getSelectedItem(),(String) this.jcoGradoAcademico.getSelectedItem(),
                        (String) this.jcoEspecialidadAcademica.getSelectedItem());

                        this.usuario.setCorreoElectronico(this.jtxtCorreoElectronico.getText());
                        usuarioBO.actualizar2(this.getUsuario());
                        
                        docenteBO.actualizar(docente);

                        JOptionPane.showMessageDialog(null, "Docente actualizado satisfactoriamente");
                        
                        this.setDocente(docente);
                        this.setUsuario(usuarioBO.buscarPorDni(this.getDocente().getDni()));
                    }
                    break;
                case 1:
                    if(this.jtxtDNI.getText().equals("")){
                        JOptionPane.showMessageDialog(null, "Error, ingrese el DNI del Estudiante");
                    }
                    else if(this.jtxtDNI.getText().length()!=8){
                        JOptionPane.showMessageDialog(null, "Error, el DNI del Estudiante ingresado no posee la cantidad de caracteres adecuada (8)");
                    }
                    else if(this.jtxtNombre.getText().equals("")){
                         JOptionPane.showMessageDialog(null, "Error, ingrese el nombre del Estudiante");
                    }
                    else if(this.jtxtApellidoPaterno.getText().equals("")){
                         JOptionPane.showMessageDialog(null, "Error, ingrese el apellido paterno del Estudiante");
                    }
                    else if(this.jtxtApellidoMaterno.getText().equals("")){
                         JOptionPane.showMessageDialog(null, "Error, ingrese el apellido materno del Estudiante");
                    }
                    else if(this.jcaFechaNacimiento.getDate()==null){
                        JOptionPane.showMessageDialog(null, "Error, ingrese la fecha de nacimiento del Estudiante");
                    }
                    else if(this.jtxtNumeroTelefonico.getText().equals("")){
                        JOptionPane.showMessageDialog(null, "Error, ingrese el número telefónico del Estudiante");
                    }
                    else if(this.jtxtNumeroTelefonico.getText().length()!=9){
                        JOptionPane.showMessageDialog(null, "Error, el número telefónico del Estudiante ingresado no posee la cantidad de caracteres adecuada (9)");
                    }
                    else if(this.jtxtCorreoElectronico.getText().equals("")){
                        JOptionPane.showMessageDialog(null, "Error, ingrese el correo electrónico del Estudiante");
                    }
                    else if(!ValidatorUsuario.isEmail(this.jtxtCorreoElectronico.getText())){
                        JOptionPane.showMessageDialog(null, "Error, el correo electrónico del Docente posee un formato no adecuado");
                    }
                    else{
                        UsuarioBO usuarioBO = new UsuarioBO();
                        EstudianteBO estudianteBO = new EstudianteBO();
                        
                        Estudiante estudiante = new Estudiante(this.getEstudiante().getIdMiembro(),this.jtxtDNI.getText(),this.jtxtNombre.getText(),this.jtxtApellidoPaterno.getText(),this.jtxtApellidoMaterno.getText(),
                        this.jcaFechaNacimiento.getDate(),this.jtxtNumeroTelefonico.getText(),(String) this.jcoGenero.getSelectedItem());

                        this.usuario.setCorreoElectronico(this.jtxtCorreoElectronico.getText());
                        usuarioBO.actualizar2(this.getUsuario());

                        estudianteBO.actualizar(estudiante);

                        JOptionPane.showMessageDialog(null, "Estudiante registrado satisfactoriamente");
                        
                        this.setEstudiante(estudiante);
                        this.setUsuario(usuarioBO.buscarPorDni(this.getEstudiante().getDni()));
                    }
                    break;
            }
        }
        catch(Exception e){
            if(e.getMessage().contains("idx_docente_dni")){
                JOptionPane.showMessageDialog(null, "El DNI ingresado del docente ya existe en la base de datos");
            }
            if(e.getMessage().contains("idx_docente_numero_telefonico")){
                JOptionPane.showMessageDialog(null, "El numero telefonico del docente ingresado ya existe en la base de datos");
            }
            
            if(e.getMessage().contains("idx_estudiante_dni")){
                JOptionPane.showMessageDialog(null, "El DNI ingresado del estudiante ya existe en la base de datos");
            }
            if(e.getMessage().contains("idx_estudiante_numero_telefonico")){
                JOptionPane.showMessageDialog(null, "E-003: El numero telefonico ingresado del estudiante ya existe en la base de datos");
            }
            
            if(e.getMessage().contains("idx_usuario_correo_electronico")){
                JOptionPane.showMessageDialog(null, "El correo electronico ingresado ya existe en la base de datos");
            }
            
            e.printStackTrace();
        }        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try{
            switch(this.jcoRol.getSelectedIndex()){
                case 0:
                    DocenteBO docenteBO = new DocenteBO();
                    docenteBO.eliminar(this.getDocente().getIdMiembro());
                    JOptionPane.showMessageDialog(null, "Docente eliminado satisfactoriamente");
                    limpiarDatos();
                case 1:
                    EstudianteBO estudianteBO = new EstudianteBO();
                    estudianteBO.eliminar(this.getEstudiante().getIdMiembro());
                    JOptionPane.showMessageDialog(null, "Estudiante eliminado satisfactoriamente");
                    limpiarDatos();
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        Asignar_estudiante_auxiliar_academico ventana = new Asignar_estudiante_auxiliar_academico();
        ventana.setDni(dni);
        ventana.setNombreCompleto(nombreCompleto);
        ventana.setCorreoElectronico(correoElectronico);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    public String getNombreCompleto() {
        return nombreCompleto;
    }

    public void setNombreCompleto(String nombreCompleto) {
        this.nombreCompleto = nombreCompleto;
        this.nombreAuxiliarA.setText(this.getNombreCompleto());
    }

    public String getCorreoElectronico() {
        return correoElectronico;
    }

    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
        this.correoAuxiliarA.setText(this.getCorreoElectronico());
    }
    
    public String getDni() {
        return dni;
    }

    public void setDni(String dni) {
        this.dni = dni;
    }

    public Estudiante getEstudiante() {
        return estudiante;
    }

    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
        this.jcoRol.setSelectedIndex(1);
        seleccionarDatosEstudiante();
    }

    public Docente getDocente() {
        return docente;
    }

    public void setDocente(Docente docente) {
        this.docente = docente;
        this.jcoRol.setSelectedIndex(0);
        seleccionarDatosDocente();
    }
    
    private void actualizarFormulario(){
        switch(this.jcoRol.getSelectedIndex()){
            case 0:
                this.jlGradoAcademico.setVisible(true);
                this.jcoGradoAcademico.setVisible(true);
                this.jlEspecialidadAcademica.setVisible(true);
                this.jcoEspecialidadAcademica.setVisible(true);
                break;
            case 1:
                this.jlGradoAcademico.setVisible(false);
                this.jcoGradoAcademico.setVisible(false);
                this.jlEspecialidadAcademica.setVisible(false);
                this.jcoEspecialidadAcademica.setVisible(false);
                break;
        }
    }
    
    private void seleccionarDatosEstudiante(){
        this.jtxtDNI.setText(this.getEstudiante().getDni());
        this.jtxtNombre.setText(this.getEstudiante().getNombre());
        this.jtxtApellidoPaterno.setText(this.getEstudiante().getApellidoPaterno());
        this.jtxtApellidoMaterno.setText(this.getEstudiante().getApellidoMaterno());
        switch(this.getEstudiante().getGenero()){
            case "Hombre":
                this.jcoGenero.setSelectedIndex(0);
                break;
            case "Mujer":
                this.jcoGenero.setSelectedIndex(1);
                break;
        }
        this.jcaFechaNacimiento.setDate(this.getEstudiante().getFechaNacimiento());
        this.jtxtNumeroTelefonico.setText(this.getEstudiante().getNumeroTelefonico());
    }
    
    private void seleccionarDatosDocente(){
        this.jtxtDNI.setText(this.getDocente().getDni());
        this.jtxtNombre.setText(this.getDocente().getNombre());
        this.jtxtApellidoPaterno.setText(this.getDocente().getApellidoPaterno());
        this.jtxtApellidoMaterno.setText(this.getDocente().getApellidoMaterno());
        switch(this.docente.getGenero()){
            case "Hombre":
                this.jcoGenero.setSelectedIndex(0);
                break;
            case "Mujer":
                this.jcoGenero.setSelectedIndex(1);
                break;
        }
        
        switch(this.docente.getGradoAcademico()){
            case "Licenciado":
                this.jcoGradoAcademico.setSelectedIndex(0);
                break;
            case "Magister":
                this.jcoGradoAcademico.setSelectedIndex(1);
                break;
            case "Doctor":
                this.jcoGradoAcademico.setSelectedIndex(2);
                break;
        }
        switch(this.docente.getEspecialidadAcademica()){
            case "Ciencias":
                this.jcoEspecialidadAcademica.setSelectedIndex(0);
                break;
            case "Humanidades":
                this.jcoEspecialidadAcademica.setSelectedIndex(1);
                break;
        }
        
        this.jcaFechaNacimiento.setDate(this.getDocente().getFechaNacimiento());
        this.jtxtNumeroTelefonico.setText(this.getDocente().getNumeroTelefonico());
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
        this.jtxtCorreoElectronico.setText(this.getUsuario().getCorreoElectronico());
    }
    
    private void limpiarDatos(){
        this.jtxtDNI.setText(null);
        this.jtxtNombre.setText(null);
        this.jtxtApellidoPaterno.setText(null);
        this.jtxtApellidoMaterno.setText(null);
        this.jcaFechaNacimiento.setDate(null);
        this.jtxtNumeroTelefonico.setText(null);
        this.jtxtCorreoElectronico.setText(null);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestionar_docente_estudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestionar_docente_estudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestionar_docente_estudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestionar_docente_estudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestionar_docente_estudiantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel correoAuxiliarA;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private com.toedter.calendar.JDateChooser jcaFechaNacimiento;
    private javax.swing.JComboBox<String> jcoEspecialidadAcademica;
    private javax.swing.JComboBox<String> jcoGenero;
    private javax.swing.JComboBox<String> jcoGradoAcademico;
    private javax.swing.JComboBox<String> jcoRol;
    private javax.swing.JLabel jlEspecialidadAcademica;
    private javax.swing.JLabel jlGradoAcademico;
    private javax.swing.JTextField jtxtApellidoMaterno;
    private javax.swing.JTextField jtxtApellidoPaterno;
    private javax.swing.JTextField jtxtCorreoElectronico;
    private javax.swing.JTextField jtxtDNI;
    private javax.swing.JTextField jtxtNombre;
    private javax.swing.JTextField jtxtNumeroTelefonico;
    private javax.swing.JLabel nombreAuxiliarA;
    // End of variables declaration//GEN-END:variables
}
